"""数据模型模块"""

from .requests import (
    GenerateFullOutlineRequest,
    GenerateVolumeOutlineRequest,
    GenerateVolumeOutlineStreamRequest,
    GenerateChapterOutlineRequest,
    WriteChapterContentRequest,
    WriteChapterContentStreamRequest,
    SummarizeChapterRequest,
    GenerateCharactersRequest,
    GenerateWorldSettingsRequest,
    GenerateTimelineEventsRequest,
    GenerateForeshadowingsRequest,
    ExtractForeshadowingsRequest,
    ExtractChapterHookRequest,
    ModifyOutlineByDialogueRequest,
)

from .responses import (
    ErrorResponse,
    HealthResponse,
    FullOutlineResponse,
    VolumeOutlineResponse,
    ModifyOutlineResponse,
    ChapterOutlineResponse,
    ChapterContentResponse,
    ChapterSummaryResponse,
    CharactersResponse,
    WorldSettingsResponse,
    TimelineEventsResponse,
    ForeshadowingsResponse,
    ChapterHookResponse,
    VolumeInfo,
    ChapterInfo,
    CharacterInfo,
    WorldSettingInfo,
    TimelineEventInfo,
    ForeshadowingInfo,
)

__all__ = [
    # Requests
    "GenerateFullOutlineRequest",
    "GenerateVolumeOutlineRequest",
    "GenerateVolumeOutlineStreamRequest",
    "GenerateChapterOutlineRequest",
    "WriteChapterContentRequest",
    "WriteChapterContentStreamRequest",
    "SummarizeChapterRequest",
    "GenerateCharactersRequest",
    "GenerateWorldSettingsRequest",
    "GenerateTimelineEventsRequest",
    "GenerateForeshadowingsRequest",
    "ExtractForeshadowingsRequest",
    "ExtractChapterHookRequest",
    "ModifyOutlineByDialogueRequest",
    # Responses
    "ErrorResponse",
    "HealthResponse",
    "FullOutlineResponse",
    "VolumeOutlineResponse",
    "ModifyOutlineResponse",
    "ChapterOutlineResponse",
    "ChapterContentResponse",
    "ChapterSummaryResponse",
    "CharactersResponse",
    "WorldSettingsResponse",
    "TimelineEventsResponse",
    "ForeshadowingsResponse",
    "ChapterHookResponse",
    # Info models
    "VolumeInfo",
    "ChapterInfo",
    "CharacterInfo",
    "WorldSettingInfo",
    "TimelineEventInfo",
    "ForeshadowingInfo",
]
